dist: trusty

git:
  depth: 1

branches:
  only:
  - master

jobs:
  include:
    - stage: deploy
      script:
      - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME --password-stdin
      - docker build -t $DOCKER_REGISTRY/$DOCKER_USERNAME/herald-skills .
      - docker push $DOCKER_REGISTRY/$DOCKER_USERNAME/herald-skills
